name: 'citibike_case_study'
version: '1.0.0'
config-version: 2

profile: 'citibike_case_study'

model-paths: ['models']
analysis-paths: ['analysis']
test-paths: ['tests']
seed-paths: ['seeds']
macro-paths: ['macros']
snapshot-paths: ['snapshots']

target-path: 'target'
clean-targets:
  - 'target'
  - 'dbt_packages'

models:
  citibike_case_study:

    staging:
      +materialized: view
      +schema: STAGE

    dimensions:
      +materialized: table
      +schema: MART

    facts:
      +materialized: table
      +schema: MART
